# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dhcpy6d
email: contact@dhcpy6d.de
description: >- # this means to ignore newlines until "baseurl:"
  Dhcpy6d delivers IPv6 addresses and prefixes for DHCPv6 clients, which can be identified by DUID,
  hostname or MAC address as in the good old IPv4 days. Addresses may be generated randomly,
  by range, by arbitrary ID or MAC address. Clients can get more than one address,
  leases and client configuration can be stored in databases and DNS can be updated dynamically.
  Range-based prefixes be delegated as well as fixed prefixes per client.
  Runs well on Linux and *BSD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dhcpy6d.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username:  henriwahl/dhcpy6d

# Build settings
markdown: kramdown
#theme: minima
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

rss: rss feed
feed:
  path: feed

# just-the-docs settings from https://pmarsceill.github.io/just-the-docs/docs/configuration
search:
  button: true
  previews: 5


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
